[package]
name = "SwitchShuttle"
version = "1.0.1"
edition = "2021"

[dependencies]
tauri = { version = "1.7.1", features = [ "fs-all", "path-all", "window-all", "shell-sidecar", "shell-execute", "system-tray", "shell-open", "wry", "dialog"] }
tauri-plugin-context-menu = { git = "https://github.com/c2r0b/tauri-plugin-context-menu", branch = "main" }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
dirs = "5.0.1"
include_dir = "0.7"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
auto-launch = "0.5.0"
global-hotkey = "0.5"
once_cell = "1.19.0"
mouse_position = "0.1.4"


[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"

[build-dependencies]
tauri-build = { version = "1", features = [] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
